sudo: false

before_install:
- mkdir -p ~/bin
- curl -sL -o - https://github.com/commercialhaskell/stack/releases/download/v0.1.0.0/stack-0.1.0.0-x86_64-linux.gz | zcat > ~/bin
- chmod +x ~/bin/stack

install:
- ~/bin/stack build

script:
- ~/bin/stack test

cache:
  directories:
  - $HOME/bin
  - $HOME/.stack
