sudo: false

install:
- mkdir -p ~/bin
- curl -sL -o - https://github.com/commercialhaskell/stack/releases/download/v0.1.0.0/stack-0.1.0.0-x86_64-linux.gz | zcat > ~/bin/stack
- chmod +x ~/bin/stack
- ~/bin/stack setup

script: ./travis.sh

cache:
  directories:
  - $HOME/bin
  - $HOME/.stack/snapshots/x86_64-linux/lts-*

addons:
  apt:
    packages:
    - libgmp3-dev
    - upx-ucl
    - binutils

  artifacts:
    paths:
    - upcast-$TRAVIS_BUILD_NUMBER
